#! /usr/bin/env Rscript

BiocManager::install("assertthat")
require(assertthat)
BiocManager::version()
BiocManager::install("rsbml")
library(rsbml)
BiocManager::install("RCurl")
library(RCurl)
library("ShortRead")
library("GenomicAlignments")
library("GenomicFeatures")
find.package("ShortRead")
BiocManager::install("XML")
library(XML)
BiocManager::install("EBImage")
library(EBImage)
BiocManager::install("RMySQL")
library(RMySQL)
BiocManager::install("DirichletMultinomial")
library(DirichletMultinomial)
BiocManager::install("rjags")
library("rjags")
BiocManager::install("testit")
BiocManager::install("protolite")
library(protolite)

assert_that(AnVIL %in% installed.packages() == "TRUE")
assert_that(DataBiosphere/Ronaldo %in% installed.packages() == "TRUE")
assert_that(shiny %in% installed.packages() == "TRUE")
assert_that(bigrquery %in% installed.packages() == "TRUE")
assert_that(googleCloudStorageR %in% installed.packages() == "TRUE")
assert_that(tidyverse %in% installed.packages() == "TRUE")
assert_that(Seurat %in% installed.packages() == "TRUE")
assert_that(SingleCellExperiment %in% installed.packages() == "TRUE")
assert_that(GenomicFeatures %in% installed.packages() == "TRUE")
assert_that(GenomicAlignments %in% installed.packages() == "TRUE")
assert_that(ShortRead %in% installed.packages() == "TRUE")
assert_that(DESeq2 %in% installed.packages() == "TRUE")
assert_that(AnnotationHub %in% installed.packages() == "TRUE")
assert_that(ExperimentHub %in% installed.packages() == "TRUE")
assert_that(ensembldb %in% installed.packages() == "TRUE")
assert_that(scRNAseq %in% installed.packages() == "TRUE")
assert_that(scran %in% installed.packages() == "TRUE")
assert_that(Rtsne %in% installed.packages() == "TRUE")
assert_that(BiocGenerics %in% installed.packages() == "TRUE")
assert_that(S4Vectors %in% installed.packages() == "TRUE")
assert_that(BiocVersion %in% installed.packages() == "TRUE")
assert_that(GenomeInfoDb %in% installed.packages() == "TRUE")
assert_that(IRanges %in% installed.packages() == "TRUE")
assert_that(Biobase %in% installed.packages() == "TRUE")
assert_that(zlibbioc %in% installed.packages() == "TRUE")
assert_that(Biostrings %in% installed.packages() == "TRUE")
assert_that(BiocParallel %in% installed.packages() == "TRUE")
assert_that(GenomicRanges %in% installed.packages() == "TRUE")
assert_that(DelayedArray %in% installed.packages() == "TRUE")
assert_that(SummarizedExperiment %in% installed.packages() == "TRUE")
assert_that(MatrixGenerics %in% installed.packages() == "TRUE")
assert_that(limma %in% installed.packages() == "TRUE")
assert_that(AnnotationDbi %in% installed.packages() == "TRUE")
assert_that(KEGGREST %in% installed.packages() == "TRUE")
assert_that(annotate %in% installed.packages() == "TRUE")
assert_that(BiocFileCache %in% installed.packages() == "TRUE")
assert_that(genefilter %in% installed.packages() == "TRUE")
assert_that(Rhtslib %in% installed.packages() == "TRUE")
assert_that(Rsamtools %in% installed.packages() == "TRUE")
assert_that(edgeR %in% installed.packages() == "TRUE")
assert_that(biomaRt %in% installed.packages() == "TRUE")
assert_that(geneplotter %in% installed.packages() == "TRUE")
assert_that(ggtree %in% installed.packages() == "TRUE")
assert_that(rhdf5filters %in% installed.packages() == "TRUE")
assert_that(fgsea %in% installed.packages() == "TRUE")
assert_that(Rgraphviz %in% installed.packages() == "TRUE")
