@startmindmap
* terra-jupyter-base Y
** terra-jupyter-python Y
*** terra-jupyter-gatk Y
**** terra-jupyter-aou
*** terra-jupyter-hail
** terra-jupyter-r Y
*** terra-jupyter-gatk Y
*** terra-jupyter-bioconductor Y
@endmindmap
