FROM us.gcr.io/broad-dsp-gcr-public/terra-jupyter-r:2.2.0

# add env var to not use binaries
# (TEMPORARY) to fix issue with protolite https://the-anvil.slack.com/archives/C034WLKV15K/p1687889742101099
ENV BIOCONDUCTOR_USE_CONTAINER_REPOSITORY="FALSE"