name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
#     on:
  #     pull_request:
  #       branches:
#         - master  

#initial code for testing
    on:
      pull_request:
        branches:
        - jc-lint  

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm install
        eslint --fix terra-jupyter-base/custom/*.js
      env:
        CI: true
