name: Publish image to GCR
on:
  push:
  workflow_dispatch:
    inputs:
      image:
        description: 'Image to publish'
        required: true
        type: choice
        options:
          - terra-jupyter-aou
          - terra-jupyter-base
          - terra-jupyter-bioconductor
          - terra-jupyter-gatk
          - terra-jupyter-gatk-ovtf
          - terra-jupyter-hail
          - terra-jupyter-python
      version:
        description: 'version to publish'
        required: true
        default: ''
      branch:
        description: 'Branch to run the workflow on'
        required: false
        default: 'master'
env:
  SERVICE_NAME: ${{ github.event.repository.name }}
  GOOGLE_PROJECT: broad-dsp-gcr-public
jobs:
  tag-publish-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Free up some disk space
        run: sudo rm -rf /usr/share/dotnet

      - id: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          create_credentials_file: true

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.3.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Explicitly auth Docker for GCR
        run: gcloud auth configure-docker --quiet

      - name: Construct docker image name and tag
        id: image-name
        run: |
          echo ::set-output name=name::us.gcr.io/${GOOGLE_PROJECT}/${github.event.inputs.image}:${github.event.inputs.version}

      - name: Build Docker image and base images too, if needed
        run: |
          gcloud auth configure-docker
          ./build.sh ${github.event.inputs.image} ${github.event.inputs.version}

      - name: Run Trivy vulnerability scanner
        # Link to the github location of the action https://github.com/broadinstitute/dsp-appsec-trivy-action
        uses: broadinstitute/dsp-appsec-trivy-action@v1
        with:
          image: ${{ steps.image-name.outputs.name }}
      - name: Push GCR image
        run: "docker push ${{ steps.image-name.outputs.name }}"
