name: Publish image to GCR
on:
  push:
  workflow_dispatch:
    inputs:
      image:
        description: 'Image to publish'
        required: true
        type: choice
        options:
          - terra-jupyter-aou
          - terra-jupyter-base
          - terra-jupyter-bioconductor
          - terra-jupyter-gatk
          - terra-jupyter-gatk-ovtf
          - terra-jupyter-hail
          - terra-jupyter-python
        default: 'terra-jupyter-aou'
      branch:
        description: 'Branch to run the workflow on'
        required: false
        default: 'master'
env:
  SERVICE_NAME: ${{ github.event.repository.name }}
  GOOGLE_PROJECT: broad-dsp-gcr-public
jobs:
  publish-job:
    runs-on: self-hosted
    steps:
      - name: Checkout current code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - id: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          create_credentials_file: true

#      - name: Set up Cloud SDK
#        uses: google-github-actions/setup-gcloud@v0.3.0
#        with:
#          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Explicitly auth Docker for GCR
        run: gcloud auth configure-docker --quiet

      - name: Build Docker image and publish
        run: |
          gcloud auth configure-docker
          ./build.sh ${{ github.event.inputs.image }} ${{ secrets.GCP_SA_KEY }}
