name: Test terra-jupyter-base
# Perform smoke tests on the terra-jupyter-python Docker image to have some amount of confidence that
# Python package versions are compatible.
#
# To configure the minimal auth needed for these tests to be able to read public data from Google Cloud Platform:
# Step 1: Create a service account per these instructions:
#         https://github.com/google-github-actions/setup-gcloud/blob/master/setup-gcloud/README.md
# Step 2: Give the service account the following permissions within the project: BigQuery User
# Step 3: Store its key and project id as GitHub repository secrets TD_GCP_SA_KEY and GCP_PROJECT_ID.
#         https://docs.github.com/en/free-pro-team@latest/actions/reference/encrypted-secrets#creating-encrypted-secrets-for-a-repository

on:
  pull_request:
    branches: [ master ]
    paths:
    - 'terra-jupyter-base/**'
    - '.github/workflows/test-terra-jupyter-base.yml'

  push:
    # Note: GitHub secrets are not passed to pull requests from forks. For community contributions from
    # regular contributors, its a good idea for the contributor to configure the GitHub actions to run correctly
    # in their fork as described above.
    #
    # For occasional contributors, the dev team will merge the PR fork branch to a branch in upstream named
    # test-community-contribution-<PR#> to run all the GitHub Action smoke tests.
    branches: [ 'test-community-contribution*' ]
    paths:
    - 'terra-jupyter-base/**'
    - '.github/workflows/test-terra-jupyter-base.yml'

  workflow_dispatch:
    # Allows manually triggering of workflow on a selected branch via the GitHub Actions tab.
    # GitHub blog demo: https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/.

env:
  GOOGLE_PROJECT: ${{ secrets.GCP_PROJECT_ID }}

jobs:

  test_docker_image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Free up some disk space
      run: sudo rm -rf /usr/share/dotnet

    - id: auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.TD_GCP_SA_KEY }}
        create_credentials_file: true

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.3.0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Build Docker image and base images too, if needed
      run: |
        gcloud auth configure-docker
        ./build_smoke_test_image.sh terra-jupyter-base

    - name: Upload workflow artifacts
      uses: actions/upload-artifact@v2
      with:
        name: notebook-execution-results
        path: terra-jupyter-base/tests/*.html
        retention-days: 30

    - name: Test Python code with pytest
      run: |
        chmod a+r "${{ steps.auth.outputs.credentials_file_path }}"
        docker run \
          --env GOOGLE_PROJECT \
          --volume "${{ steps.auth.outputs.credentials_file_path }}":/tmp/credentials.json:ro \
          --env GOOGLE_APPLICATION_CREDENTIALS="/tmp/credentials.json" \
          --volume $GITHUB_WORKSPACE/terra-jupyter-base/tests:/tests \
          --workdir=/tests \
          --entrypoint="" \
          terra-jupyter-base:smoke-test \
          /bin/sh -c "pip3 --force-reinstall install pytest; pytest"
